volumes:
  postgres_data:

services:
  postgres:
    image: postgres:18
    container_name: dnd_guide_postgres
    env_file:
      - .postgres.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/18/docker
